version: '3.8'

networks:
  dev:

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: >
      sh -c "cp /etc/letsencrypt/archive/sibplc-kis3.ru/fullchain2.pem /etc/nginx/ssl/fullchain.pem &&
             cp /etc/letsencrypt/archive/sibplc-kis3.ru/privkey2.pem /etc/nginx/ssl/privkey.pem &&
             chmod 644 /etc/nginx/ssl/fullchain.pem &&
             chmod 600 /etc/nginx/ssl/privkey.pem &&
             nginx -g 'daemon off;'"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - dev