version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - /etc/letsencrypt/live/sibplc-kis3.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/sibplc-kis3.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Добавляем маппинг портов
    networks:
      - dev


# конец
