version: '3.8'

networks:
  dev:

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    command: >
      sh -c "
      echo 'Listing /etc/letsencrypt directory:' &&
      ls -R /etc/letsencrypt &&
      fullchain=$(find /etc/letsencrypt -name 'fullchain*.pem' | sort -V | tail -n 1) &&
      privkey=$(find /etc/letsencrypt -name 'privkey*.pem' | sort -V | tail -n 1) &&
      echo 'Fullchain path:' $fullchain &&
      echo 'Privkey path:' $privkey &&
      if [ -f "$fullchain" ] && [ -f "$privkey" ]; then
        cp $fullchain /etc/nginx/ssl/fullchain.pem &&
        cp $privkey /etc/nginx/ssl/privkey.pem &&
        chmod 644 /etc/nginx/ssl/fullchain.pem &&
        chmod 600 /etc/nginx/ssl/privkey.pem &&
        echo 'Certificates copied successfully' &&
        ls -l /etc/nginx/ssl/
      else
        echo 'Certificate files not found'
      fi &&
      nginx -g 'daemon off;'"
    user: root
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - dev