version: '3.8'

networks:
  dev:

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/archive/sibplc-kis3.ru/fullchain2.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/archive/sibplc-kis3.ru/privkey2.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - dev