"""add timings

Revision ID: 2e11c31de0bd
Revises: 68ee961e8ddd
Create Date: 2025-03-21 11:58:44.701462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e11c31de0bd'
down_revision: Union[str, None] = '68ee961e8ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_serial', sa.String(length=16), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Interval(), nullable=False),
    sa.Column('timing_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['order_serial'], ['orders.serial'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timings')
    # ### end Alembic commands ###
