"""add change task

Revision ID: 331729a5069a
Revises: c224ba1efb45
Create Date: 2025-03-17 15:24:37.837574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '331729a5069a'
down_revision: Union[str, None] = 'c224ba1efb45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('payment_status_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_TaskPaymentStatus_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'payment_statuses', ['payment_status_id'], ['id'])
    op.drop_column('tasks', 'TaskPaymentStatus_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('TaskPaymentStatus_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_TaskPaymentStatus_id_fkey', 'tasks', 'payment_statuses', ['TaskPaymentStatus_id'], ['id'])
    op.drop_column('tasks', 'payment_status_id')
    # ### end Alembic commands ###
