"""fix task name unique

Revision ID: 53040178f872
Revises: f6820aa58e73
Create Date: 2025-03-18 16:28:12.992776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53040178f872'
down_revision: Union[str, None] = 'f6820aa58e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_name_key', 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tasks_name_key', 'tasks', ['name'])
    # ### end Alembic commands ###
