"""edit task

Revision ID: 6f2e70d97840
Revises: 331729a5069a
Create Date: 2025-03-17 21:41:29.690878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2e70d97840'
down_revision: Union[str, None] = '331729a5069a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('executor_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('planned_duration', sa.Interval(), nullable=True))
    op.add_column('tasks', sa.Column('actual_duration', sa.Interval(), nullable=True))
    op.add_column('tasks', sa.Column('creation_moment', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('start_moment', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('deadline_moment', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('end_moment', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('order_serial', sa.String(length=16), nullable=True))
    op.add_column('tasks', sa.Column('parent_task_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('root_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'people', ['executor_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'tasks', ['root_task_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'orders', ['order_serial'], ['serial'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'root_task_id')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'order_serial')
    op.drop_column('tasks', 'price')
    op.drop_column('tasks', 'end_moment')
    op.drop_column('tasks', 'deadline_moment')
    op.drop_column('tasks', 'start_moment')
    op.drop_column('tasks', 'creation_moment')
    op.drop_column('tasks', 'actual_duration')
    op.drop_column('tasks', 'planned_duration')
    op.drop_column('tasks', 'executor_id')
    # ### end Alembic commands ###
