"""fix relationship

Revision ID: 941bc62905e9
Revises: 694365c01474
Create Date: 2025-03-20 10:44:26.837098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941bc62905e9'
down_revision: Union[str, None] = '694365c01474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_cabinet_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_cabinets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('ip_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['ip_id'], ['ips.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['control_cabinet_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('equipment', sa.Column('discriminator', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'discriminator')
    op.drop_table('control_cabinets')
    op.drop_table('ips')
    op.drop_table('control_cabinet_materials')
    # ### end Alembic commands ###
