"""rename

Revision ID: 9a44535aef98
Revises: cc0d65a95f5a
Create Date: 2024-10-03 21:42:24.083207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a44535aef98'
down_revision: Union[str, None] = 'cc0d65a95f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_on_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=16), nullable=False),
    sa.Column('moment_of_creation', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.serial'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_comment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('moment_of_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.serial'], name='order_comment_order_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name='order_comment_person_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_comment_pkey')
    )
    op.drop_table('comments_on_orders')
    # ### end Alembic commands ###
