"""поправил учёт шкафооов

Revision ID: ba4a6b77ddbc
Revises: dd4443b0e776
Create Date: 2024-10-01 22:55:59.016289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4a6b77ddbc'
down_revision: Union[str, None] = 'dd4443b0e776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('box_accounting', 'programmer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'box_accounting', ['serial_num'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'box_accounting', type_='unique')
    op.alter_column('box_accounting', 'programmer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
