"""Добавлено поле UUID в Person

Revision ID: c5aa2a28d350
Revises: 2e11c31de0bd
Create Date: 2025-03-22 02:19:16.722230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5aa2a28d350'
down_revision: Union[str, None] = '2e11c31de0bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Добавляем временно NULLABLE столбец
    op.add_column('people', sa.Column('uuid', sa.UUID(), nullable=True))

    # Проставляем случайные UUID для существующих записей
    op.execute('UPDATE people SET uuid = gen_random_uuid()')

    # Делаем колонку NOT NULL
    op.alter_column('people', 'uuid', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'uuid')
    # ### end Alembic commands ###
