"""Добавил учёт шкафов

Revision ID: dd4443b0e776
Revises: 62eeb4ad8d75
Create Date: 2024-10-01 21:24:27.888695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4443b0e776'
down_revision: Union[str, None] = '62eeb4ad8d75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('box_accounting',
    sa.Column('serial_num', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=16), nullable=False),
    sa.Column('scheme_developer_id', sa.Integer(), nullable=False),
    sa.Column('assembler_id', sa.Integer(), nullable=False),
    sa.Column('programmer_id', sa.Integer(), nullable=False),
    sa.Column('tester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assembler_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.serial'], ),
    sa.ForeignKeyConstraint(['programmer_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['scheme_developer_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['tester_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('serial_num'),
    sa.UniqueConstraint('serial_num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('box_accounting')
    # ### end Alembic commands ###
