"""fix name for ControlCabinet

Revision ID: e7ed356c9bd2
Revises: 941bc62905e9
Create Date: 2025-03-20 10:46:48.559277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ed356c9bd2'
down_revision: Union[str, None] = '941bc62905e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('control_cabinets', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_cabinets', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
